services:
  db:
    image: postgres:16-alpine
    container_name: classroom_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: classroom_booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

volumes:
  pgdata:
